<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>EmniProgress</PackageId>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageLicenseExpression>Unlicense</PackageLicenseExpression>

        <MinVerTagPrefix>v</MinVerTagPrefix>
        <MinVerDefaultPreReleaseIdentifiers>alpha.0</MinVerDefaultPreReleaseIdentifiers>
        <Authors>igemily</Authors>
        <Company>SillyTeamInc</Company>
        <Description>Simple C# library for integrating with KDE jobs.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Tmds.DBus" Version="0.92.0" />
        <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>